language: php

php:
  - 5.3
  - 5.4

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - composer selfupdate
  - composer install --no-interaction
  - echo 'xdebug.max_nesting_level = 250' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: phpunit -c app
