language: php

php:
  - 5.6
  - 7.0

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo "memory_limit = 1024M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp app/config/security.test.yml app/config/security.yml
  - composer selfupdate
  - composer install --no-interaction

script: vendor/bin/phpunit
