language: php

php:
  - 5.3
  - 5.4

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cp app/config/parameters.default.yml app/config/parameters.yml
  - composer selfupdate
  - composer install --no-interaction

script: phpunit -c app
