# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../web
    filters:
        lessphp:
            file:       %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to:   '\.less$'
        cssrewrite: ~
        cssembed:
            jar:        %kernel.root_dir%/../vendor/packagist/cssembed-bin/bin/cssembed.jar
            apply_to:   '\.css$'
        yui_css:
            jar:        %kernel.root_dir%/../vendor/packagist/yuicompressor-bin/bin/yuicompressor.jar
            apply_to:   '\.css$'
        yui_js:
            jar:        %kernel.root_dir%/../vendor/packagist/yuicompressor-bin/bin/yuicompressor.jar
    assets:
        # FontAwesome
        FontAwesome-eot:
            inputs:
                -       %kernel.root_dir%/../bower_components/fontawesome/fonts/fontawesome-webfont.eot
            output:     'font/fontawesome-webfont.eot'
        FontAwesome-svg:
            inputs:
                -       %kernel.root_dir%/../bower_components/fontawesome/fonts/fontawesome-webfont.svg
            output:     'font/fontawesome-webfont.svg'
        FontAwesome-ttf:
            inputs:
                -       %kernel.root_dir%/../bower_components/fontawesome/fonts/fontawesome-webfont.ttf
            output:     'font/fontawesome-webfont.ttf'
        FontAwesome-woff:
            inputs:
                -       %kernel.root_dir%/../bower_components/fontawesome/fonts/fontawesome-webfont.woff
            output:     'font/fontawesome-webfont.woff'
