imports:
    - { resource: config.yml }
    - { resource: security.yml }

doctrine:
    orm:
        metadata_cache_driver:
            type: "%cache_driver%"
            host: "%cache_host%"
            port: "%cache_port%"
        result_cache_driver:
            type: "%cache_driver%"
            host: "%cache_host%"
            port: "%cache_port%"
        query_cache_driver:
            type: "%cache_driver%"
            host: "%cache_host%"
            port: "%cache_port%"

monolog:
    handlers:
        main:
            type: syslog
            level: info
            facility: local7
            ident: "sfl-labdb[%kernel.environment%]"
            logopts: 0
