imports:
    - { resource: parameters.yml }
    - { resource: assets.yml }

framework:
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'VIBFormsBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

mopa_bootstrap:
    initializr:
        meta:
            title:        "FlyDB"
            description:  "Fly stock management system"
            keywords:     "FlyDB,management,stock"
            author_name:  "Radosław Kamil Ejsmont"
            author_url:   "http://radoslaw.ejsmont.net/"
            nofollow:     true
            noindex:      true
        dns_prefetch:
            - '//ajax.googleapis.com'
        google:
            wt:          %google_verification%
            analytics:   %google_analytics%
    navbar:
        template: 'VIBBaseBundle:Menu:main.html.twig'
    form: 
        collection:
            widget_remove_btn:
                icon: trash
            widget_add_btn:
                icon: plus-sign
        render_optional_text: false

vib_security:
    acl_walker: VIB\SecurityBundle\Bridge\Doctrine\AclWalker

shibboleth:
    handler_path: /Shibboleth.sso
    secured_handler: true
    session_initiator_path: /Login

fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: VIB\UserBundle\Entity\User
