bluemesa_sensor:
    resource: "@BluemesaSensorBundle/Controller/"
    type:     annotation
    prefix:   /sensors

bluemesa_construct:
    resource: "@BluemesaConstructBundle/Controller/"
    type:     annotation

default:
    path:  /
    defaults: { _controller: BluemesaWelcomeBundle:Default:index }
    
vib_search:
    resource: "@BluemesaSearchBundle/Controller/"
    type:     annotation
    prefix:   /
    
bluemesa_acl:
    resource: "@BluemesaAclBundle/Controller/"
    type:     annotation
    prefix:   /_ajax

bluemesa_core:
    resource: "@BluemesaCoreBundle/Controller/"
    type:     annotation
    prefix:   /_ajax

vib_flies:
    resource: "@BluemesaFliesBundle/Controller/"
    type:     annotation
    prefix:   /flies

vib_antibody:
    resource: "@BluemesaAntibodyBundle/Controller/"
    type:     annotation
    prefix:   /antibodies

vib_calendar:
    resource: "@BluemesaCalendarBundle/Controller/"
    type:     annotation
    prefix:   /calendar
    
bluemesa_users:
    resource: "@BluemesaUserBundle/Controller/"
    type:     annotation
    prefix:   /users

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

bluemesa_imap_auth:
    resource: "@BluemesaImapAuthenticationBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path:   /login
    defaults:  { _controller: BluemesaSecurityBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /logout
