vib_antibody:
    resource: "@VIBAntibodyBundle/Controller/"
    type:     annotation
    prefix:   /secure

vib_calendar:
    resource: "@VIBCalendarBundle/Controller/"
    type:     annotation
    prefix:   /

default:
    pattern:  /
    defaults: { _controller: VIBWelcomeBundle:Default:index }
vib_forms:
    resource: "@VIBFormsBundle/Resources/config/routing.yml"
    prefix:   /secure
vib_flies:
    resource: "@VIBFliesBundle/Resources/config/routing.yml"
    prefix:   /secure

login:
    pattern:   /login
    defaults:  { _controller: VIBSecurityBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /secure/logout
