vib_forms:
    resource: "@VIBFormsBundle/Resources/config/routing.yml"
vib_flies:
    resource: "@VIBFliesBundle/Resources/config/routing.yml"

login:
    pattern:   /login
    defaults:  { _controller: VIBSecurityBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout