default:
    pattern:  /
    defaults: { _controller: VIBWelcomeBundle:Default:index }
    
vib_search:
    resource: "@VIBSearchBundle/Controller/"
    type:     annotation
    prefix:   /
    
vib_forms:
    resource: "@VIBFormsBundle/Controller/"
    type:     annotation
    prefix:   /_ajax

vib_flies:
    resource: "@VIBFliesBundle/Controller/"
    type:     annotation
    prefix:   /flies

vib_antibody:
    resource: "@VIBAntibodyBundle/Controller/"
    type:     annotation
    prefix:   /antibodies

vib_calendar:
    resource: "@VIBCalendarBundle/Controller/"
    type:     annotation
    prefix:   /calendar

login:
    pattern:   /login
    defaults:  { _controller: VIBSecurityBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
