vib_imap_user:
    resource: "@VIBImapUserBundle/Controller/"
    type:     annotation
    prefix:   /

default:
    path:  /
    defaults: { _controller: VIBWelcomeBundle:Default:index }
    
vib_search:
    resource: "@VIBSearchBundle/Controller/"
    type:     annotation
    prefix:   /
    
vib_forms:
    resource: "@VIBFormsBundle/Controller/"
    type:     annotation
    prefix:   /_ajax

vib_flies:
    resource: "@VIBFliesBundle/Controller/"
    type:     annotation
    prefix:   /flies

vib_antibody:
    resource: "@VIBAntibodyBundle/Controller/"
    type:     annotation
    prefix:   /antibodies

vib_calendar:
    resource: "@VIBCalendarBundle/Controller/"
    type:     annotation
    prefix:   /calendar
    
vib_users:
    resource: "@VIBUserBundle/Controller/"
    type:     annotation
    prefix:   /users

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

login:
    path:   /login
    defaults:  { _controller: VIBSecurityBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /logout
