security:

    encoders:
        Symfony\Component\Security\Core\User\User:           plaintext
        Bluemesa\Bundle\ImapUserBundle\User\UserInterface:   plaintext
        FOS\UserBundle\Model\UserInterface:                  sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [imap_gmail]
        imap_gmail:
            id: bluemesa.user_provider.gmail_imap

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            bluemesa_imap:
                check_path: login_check
                login_path: login
                csrf_manager: security.csrf.token_manager
                provider: chain_provider
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/flies, roles: ROLE_USER }
        - { path: ^/antibodies, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    acl:
        connection: default

services:
    user_provider:
        alias: security.user.provider.concrete.chain_provider

fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: Bluemesa\Bundle\ImapAuthenticationBundle\Entity\ImapUser

bluemesa_imap_authentication:
    connections:
        -
            host:          imap.gmail.com
            port:          993
            encryption:    ssl
            validate_cert: false
            secure:        false
            domains:       ['gmail.com']
