vial:
    resource: "@VIBFliesBundle/Controller/VialController.php"
    type:     annotation

cross_vial:
    resource: "@VIBFliesBundle/Controller/CrossVialController.php"
    type:     annotation

injection_vial:
    resource: "@VIBFliesBundle/Controller/InjectionVialController.php"
    type:     annotation

stock_vial:
    resource: "@VIBFliesBundle/Controller/StockVialController.php"
    type:     annotation

stock:
    resource: "@VIBFliesBundle/Controller/StockController.php"
    type:     annotation

rack:
    resource: "@VIBFliesBundle/Controller/RackController.php"
    type:     annotation

incubator:
    resource: "@VIBFliesBundle/Controller/IncubatorController.php"
    type:     annotation

ajax:
    resource: "@VIBFliesBundle/Controller/AJAXController.php"
    type:     annotation

search:
    resource: "@VIBFliesBundle/Controller/SearchController.php"
    type:     annotation

print:
    resource: "@VIBFliesBundle/Controller/PrintController.php"
    type:     annotation
