vial:
    resource: "@VIBFliesBundle/Controller/VialController.php"
    type:     annotation

cross_vial:
    resource: "@VIBFliesBundle/Controller/CrossVialController.php"
    type:     annotation

stock_vial:
    resource: "@VIBFliesBundle/Controller/StockVialController.php"
    type:     annotation

stock:
    resource: "@VIBFliesBundle/Controller/StockController.php"
    type:     annotation
    
rack:
    resource: "@VIBFliesBundle/Controller/RackController.php"
    type:     annotation

ajax:
    resource: "@VIBFliesBundle/Controller/AJAXController.php"
    type:     annotation
    
search:
    resource: "@VIBFliesBundle/Controller/SearchController.php"
    type:     annotation

autoprint:
    resource: "@VIBFliesBundle/Controller/AutoPrintController.php"
    type:     annotation
